export const Questions = [
	{
		prompt: "333'ün 3 katı, 333'ün 3'te birinden kaç fazladır?",
		optionA: " 0",
		optionB: "222",
		optionC: "555",
		optionD: "888",
		answer: "D",
	},
	{
		prompt: '"Büyük Britanya\'daki başkentleri gezdim" diyen biri hangi şehre gittiğini söylemiş olmaz?',
		optionA: "Londra",
		optionB: "Dublin",
		optionC: "Cardiff",
		optionD: "Edinburg",
		answer: "B",
	},
	{
		prompt: "Hangi ünlü çizgi karakter genellikle sarı renkli bir şapka takar?",
		optionA: "Kirpi Sonic",
		optionB: "Hızlı Gonzales",
		optionC: "Road Runner",
		optionD: "Tazmanya Canavarı",
		answer: "B",
	},
	{
		prompt: '"Ara vermeden, sürekli olarak" anlamlarına gelen kelimenin doğru yazılışı hangisidir?',
		optionA: "Mütammadiyen",
		optionB: "Mütemnadiyen",
		optionC: "Mütemadiyen",
		optionD: "Müttemaddiyyen",
		answer: "C",
	},
	{
		prompt: "Ed Sheeran, çocukken yaşadığı kekemelik sorununu yenmesinde kimin bir albümündeki şarkıları dinleyip tüm sözlerini öğrenmesinin büyük faydası olduğunu söylemiştir?",
		optionA: "Snoop Dogg",
		optionB: "50 Cent",
		optionC: "Eminem",
		optionD: "Ceza",
		answer: "C",
	},
	{
		prompt: "Anorak, hangisinin bir çeşididir?",
		optionA: "Topuklu ayakkabı",
		optionB: "Spor ceket",
		optionC: "Kot pantolon",
		optionD: "Yün bere",
		answer: "B",
	},
	{
		prompt: "Hangi romanın yazarı John Steinbeck değildir?",
		optionA: "Fareler ve İnsanlar",
		optionB: "İnci",
		optionC: "Gazap Üzümleri",
		optionD: "Hayvan Çiftliği",
		answer: "D",
	},
	{
		prompt: "Hangi ülkede bir evin kapısını tıklatıp kaçmak suçtur?",
		optionA: "Birleşik Krallık",
		optionB: "Çin",
		optionC: "Küba",
		optionD: "Danimarka",
		answer: "A",
	},
	{
		prompt: "Morgan Freeman, kariyerindeki tek Oscar'ı hangi filmdeki rolüyle kazanmıştır?",
		optionA: "Milyonluk Bebek",
		optionB: "Esaretin Bedeli",
		optionC: "Yedi",
		optionD: "Affedilmeyen",
		answer: "A",
	},
	{
		prompt: "Tamamen otomatik sistemlerle donatılmış ve üretim gerçekleştirirken insan gücüne ihtiyaç duyulmamasını hedefleyen üretim yöntemine ne ad verilir?",
		optionA: "Karanlık fabrikalar",
		optionB: "Soğuk fabrikalar",
		optionC: "Sessiz fabrikalar",
		optionD: "Tatsız fabrikalar",
		answer: "A",
	},
];
